apiVersion: v1            # Service API
kind: Service             # We are creating a Service

metadata:
  name: order-service     # Name of the Service

spec:
  selector:
    app: order            # Find pods with this label

  ports:
    - protocol: TCP
      port: 3003          # Service port
      targetPort: 3003    # Container port

  type: ClusterIP       # Expose inside cluster