apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: user

  template:
    metadata:
      labels:
        app: user

    spec:
      containers:
        - name: user-container
          image: xoryush/user-service:02
          ports:
            - containerPort: 3001